---
name: Traefik
version: dev
slug: addon-traefik
description: Traefik is a modern reverse proxy and load balancer that makes deploying microservices easy.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "ghcr.io/dcode/addon-traefik-{arch}"
startup: system
init: false
url: https://github.com/dcode/home-assistant-addons/tree/master/traefik
ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
ingress: true
ingress_entry: dashboard/
hassio_api: true
panel_icon: mdi:earth-arrow-right
map:
  - homeassistant_config
  - share
  - ssl:rw
options:
  log_level: info
  access_logs: false
  forwarded_headers_insecure: false
  http_sanitize_path: false
  dynamic_configuration_path: "/homeassistant/traefik/"
  letsencrypt:
    enabled: false
    resolvers: []
  plugins: []
  env_vars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
  http_sanitize_path: bool
  dynamic_configuration_path: str
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
      - str?
  plugins:
    - name: str?
      moduleName: str?
      version: str?
  env_vars:
    - str
