---
name: Rclone
version: dev
slug: addon-rclone
description: Rclone is a command line program to sync files and directories to and from various providers.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: once
boot: manual
url: https://github.com/dcode/home-assistant-addons/tree/main/rclone
hassio_api: true
map:
  - backup:rw
  - addon_config:rw
  - share:rw
options:
  configuration_path: "/share/rclone/rclone.conf"
  local_retention_days: 60
  remotes:
    - name: ""
      path: "/"
      retention_days: 14
schema:
  configuration_path: str
  local_retention_days: int
  remotes:
    - name: str
      path: str
      retention_days: int
