---
name: Gabb Wireless
version: "edge"
slug: addon-gabbwireless
description: Gabb Wireless provides cellular devices for kids with parental controls.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "ghcr.io/dcode/addon-gabbwireless"
init: false
url: https://github.com/dcode/home-assistant-addons/tree/main/gabbwireless
homeassistant_api: true
panel_icon: mdi:devices
map:
  - addon_config:rw
  - share
  - ssl:rw
options:
  log_level: info
  refresh_rate: 1
  env_vars: []
schema:
  log_level: list(debug|info|warning|error|fatal)
  gabb_username: email
  gabb_password: password
  refresh_rate: int(1,)
  env_vars:
    - "match(^\\w+=.+$)" # Only allow VAR=VALUE
services:
  - mqtt:need
