---
build_from:
  aarch64: ghcr.io/hassio-addons/addon-base-python/aarch64:16.1.3
  amd64: ghcr.io/hassio-addons/addon-base-python/amd64:16.1.3
  armhf: ghcr.io/hassio-addons/addon-base-python/armhf:16.1.3
  armv7: ghcr.io/hassio-addons/addon-base-python/armv7:16.1.3
  i386: ghcr.io/hassio-addons/addon-base-python/i386:16.1.3
