---
name: Deploy

concurrency:
  group: queue

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      slug:
        description: Overrides the detected slug
        required: false
        type: string
      repository:
        default: "repository"
        description: The name of the stable repository
        required: false
        type: string
      repository_edge:
        default: "repository-edge"
        description: The name of the edge repository
        required: false
        type: string
      repository_beta:
        default: "repository-beta"
        description: The name of the beta repository
        required: false
        type: string
    secrets:
      DISPATCH_TOKEN:
        required: true

jobs:
  information:
    if: |
      github.event_name == 'release'
      || (
        github.event_name == 'workflow_run'
        && github.event.workflow_run.conclusion == 'success'
      )
    name: ℹ️ Gather add-on information
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.information.outputs.architectures }}
      base_image_signer: ${{ steps.information.outputs.codenotary_base_image }}
      build: ${{ steps.information.outputs.build }}
      description: ${{ steps.information.outputs.description }}
      environment: ${{ steps.release.outputs.environment }}
      name: ${{ steps.information.outputs.name }}
      signer: ${{ steps.information.outputs.codenotary_signer }}
      slug: ${{ steps.override.outputs.slug }}
      target: ${{ steps.information.outputs.target }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run add-on information action
        id: information
        uses: frenck/action-addon-information@v1.4.2
      - name: 🚀 Process possible slug override
        id: override
        run: |
          slug="${{ steps.information.outputs.slug }}"
          if [[ ! -z "${{ inputs.slug }}" ]]; then
            slug="${{ inputs.slug }}"
          fi
          echo "slug=$slug" >> "$GITHUB_OUTPUT"
      - name: ℹ️ Gather version and environment
        id: release
        run: |
          sha="${{ github.sha }}"
          environment="edge"
          version="${sha:0:7}"
          if [[ "${{ github.event_name }}" = "release" ]]; then
            version="${{ github.event.release.tag_name }}"
            version="${version,,}"
            version="${version#v}"
            environment="stable"
            if [[ "${{ github.event.release.prerelease }}" = "true" ]]; then
              environment="beta"
            fi
          fi

          echo "environment=${environment}" >> "$GITHUB_OUTPUT"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

  deploy:
    name: 👷 Build & Deploy ${{ matrix.architecture }}
    needs: information
    runs-on: ${{ contains(fromJson('["armhf", "armv7", "aarch64"]'), matrix.architecture) && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    strategy:
      matrix:
        architecture: ${{ fromJson(needs.information.outputs.architectures) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🏗 Set up build cache
        id: cache
        uses: actions/cache@v4.2.3
        with:
          path: /tmp/.docker-cache
          key: docker-${{ matrix.architecture }}-${{ github.sha }}
          restore-keys: |
            docker-${{ matrix.architecture }}
      - name: 🏗 Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: 🏗 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: ℹ️ Compose build flags
        id: flags
        run: |
          echo "date=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_OUTPUT"
          from=$(yq --no-colors eval ".build_from.${{ matrix.architecture }}" "${{ needs.information.outputs.build }}")
          echo "from=${from}" >> "$GITHUB_OUTPUT"

          if [[ "${{ matrix.architecture}}" = "amd64" ]]; then
            echo "platform=linux/amd64" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "i386" ]]; then
            echo "platform=linux/386" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "armhf" ]]; then
            echo "platform=linux/arm/v6" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "armv7" ]]; then
            echo "platform=linux/arm/v7" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "aarch64" ]]; then
            echo "platform=linux/arm64/v8" >> "$GITHUB_OUTPUT"
          else
            echo "::error ::Could not determine platform for architecture ${{ matrix.architecture }}"
            exit 1
          fi
      - name: 🏗  Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compose build args
        id: buildargs
        run: |
          set -eo pipefail

          COMBINED_ARGS_TEMP_FILE=$(mktemp)
          # Ensure cleanup on exit, even if script fails
          trap 'rm -f "$COMBINED_ARGS_TEMP_FILE"' EXIT

          {
            # Part 1: Args from build.yaml (e.g., needs.information.outputs.build)
            # yq extracts the .args map, formats as 'key: value' lines, then sed converts to 'key=value'.
            # If '.args' is not present or empty in the build YAML, this command sequence produces no output and exits cleanly.
            yq --no-colors '.args | to_entries | .[] | .key + ": " + .value' "${{ needs.information.outputs.build }}" | sed -r 's#: #=#'

            # Part 2: Static args
            # Each echo adds a KEY=VALUE pair followed by a newline.
            echo "BUILD_ARCH=${{ matrix.architecture }}"
            echo "BUILD_DATE=${{ steps.flags.outputs.date }}"
            echo "BUILD_DESCRIPTION=${{ needs.information.outputs.description }}"
            echo "BUILD_FROM=${{ steps.flags.outputs.from }}"
            echo "BUILD_NAME=${{ needs.information.outputs.name }}"
            echo "BUILD_REF=${{ github.sha }}"
            echo "BUILD_REPOSITORY=${{ github.repository }}"
            echo "BUILD_VERSION=${{ needs.information.outputs.version }}"
          } > "$COMBINED_ARGS_TEMP_FILE"

          echo -n "args=" >> "$GITHUB_OUTPUT"
          # Filter out any blank lines from the final list of arguments
          awk 'NF' "$COMBINED_ARGS_TEMP_FILE" >> "$GITHUB_OUTPUT"
      - name: ⤵️ Download base image
        if: steps.flags.outputs.from != 'null'
        run: docker pull "${{ steps.flags.outputs.from }}"
      - name: 🚀 Build
        uses: docker/build-push-action@v6.18.0
        with:
          load: true
          # yamllint disable rule:line-length
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.environment }}
            ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}
          # yamllint enable rule:line-length
          context: ${{ needs.information.outputs.target }}
          file: ${{ needs.information.outputs.target }}/Dockerfile
          cache-from: |
            type=local,src=/tmp/.docker-cache
            ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:edge
          cache-to: type=local,mode=max,dest=/tmp/.docker-cache-new
          platforms: ${{ steps.flags.outputs.platform }}
          build-args: ${{ steps.buildargs.outputs.args }}

      # This ugly bit is necessary, or our cache will grow forever...
      # Well until we hit GitHub's limit of 5GB :)
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: 🚚 Swap build cache
        run: |
          rm -rf /tmp/.docker-cache
          mv /tmp/.docker-cache-new /tmp/.docker-cache
      - name: 🚀 Push
        # yamllint disable rule:line-length
        run: |
          docker push \
            "ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.environment }}"
          docker push \
            "ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}"
  manifest:
    name: 👷 Build & Deploy Multi Arch Manifest
    needs:
      - information
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🏗 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: 🚀 Create manifest
        shell: bash
        # yamllint disable rule:line-length
        run: |
          declare -a images

          for architecture in $( \
            echo '${{ needs.information.outputs.architectures }}' \
            | jq --raw-output '.[]'
          ); do
            images+=("ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}/${architecture}:${{ needs.information.outputs.version }}")
          done

          docker manifest create \
            "ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}:${{ needs.information.outputs.environment }}" \
            "${images[@]}"

          docker manifest create \
            "ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}:${{ needs.information.outputs.version }}" \
            "${images[@]}"

      - name: 🏗  Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Push
        # yamllint disable rule:line-length
        run: |
          docker manifest push \
            "ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}:${{ needs.information.outputs.environment }}"
          docker manifest push \
            "ghcr.io/${{ github.repository_owner }}/${{ needs.information.outputs.slug }}:${{ needs.information.outputs.version }}"

  publish-edge:
    name: 📢 Publish to edge repository
    if: needs.information.outputs.environment == 'edge'
    needs:
      - information
      - deploy
    environment:
      name: ${{ needs.information.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Dispatch repository updater update signal
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ inputs.repository_edge }}
          event-type: update
          client-payload: >
            {
              "addon": "${{ needs.information.outputs.slug }}",
              "name": "${{ needs.information.outputs.name }}",
              "repository": "${{ github.repository }}",
              "version": "${{ needs.information.outputs.version }}"
            }

  publish-beta:
    name: 📢 Publish to beta repository
    if: |
      needs.information.outputs.environment == 'beta' ||
      needs.information.outputs.environment == 'stable'
    needs:
      - information
      - deploy
    environment:
      name: ${{ needs.information.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Dispatch repository updater update signal
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ inputs.repository_beta }}
          event-type: update
          client-payload: >
            {
              "addon": "${{ needs.information.outputs.slug }}",
              "name": "${{ needs.information.outputs.name }}",
              "repository": "${{ github.repository }}",
              "version": "${{ github.event.release.tag_name }}"
            }

  publish-stable:
    name: 📢 Publish to stable repository
    if: needs.information.outputs.environment == 'stable'
    needs:
      - information
      - deploy
    environment:
      name: ${{ needs.information.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Dispatch repository updater update signal
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ inputs.repository }}
          event-type: update
          client-payload: >
            {
              "addon": "${{ needs.information.outputs.slug }}",
              "name": "${{ needs.information.outputs.name }}",
              "repository": "${{ github.repository }}",
              "version": "${{ github.event.release.tag_name }}"
            }
