---
name: CI

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      addon:
        description: Overrides detected changed addons
        required: false
        type: string
      slug:
        description: Overrides detected slug (for all addons built this run)
        required: false
        type: string
env:
  MONITORED_FILES: "build.yaml build.json config.yaml config.json Dockerfile rootfs"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      addons: ${{ steps.changed_addons.outputs.all_addons_json }}
      changed_addons: ${{ steps.changed_addons.outputs.changed_addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Get changed add-ons
        id: changed_addons
        run: |
          declare -a changed_addons
          declare -a all_addons

          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ ! "${all_addons[@]}" =~ $addon ]]; then
              all_addons+=("\"${addon}\",");
            fi

            # Check for changes in monitored files in this add-on
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon ]]; then
              for file in ${{ env.MONITORED_FILES }}; do
                  if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon/$file ]]; then
                    if [[ ! "${changed_addons[@]}" =~ $addon ]]; then
                      changed_addons+=("\"${addon}\",");
                    fi
                  fi
              done
            fi
          done

          # Prepare JSON array string for all addons
          all_addons_json_string=$(echo "${all_addons[@]}" | sed 's/,$//')
          if [[ -n "${all_addons_json_string}" ]]; then
            echo "all_addons_json=[${all_addons_json_string}]" | tee -a "$GITHUB_OUTPUT"
          else
            echo "all_addons_json=[]" | tee -a "$GITHUB_OUTPUT"
          fi

          # Prepare JSON array string for changed addons and set 'changed' flag
          changed_addons_json_string=$(echo "${changed_addons_array[@]}" | sed 's/,$//')
          if [[ -n "${changed_addons_json_string}" ]]; then
            echo "Changed add-ons: [${changed_addons_json_string}]";
            echo "changed=true" | tee -a "$GITHUB_OUTPUT";
            echo "changed_addons=[${changed_addons_json_string}]" | tee -a "$GITHUB_OUTPUT";
          else
            echo "No add-on had any monitored files changed (${{ env.MONITORED_FILES }})";
            echo "changed=false" | tee -a "$GITHUB_OUTPUT"; # Explicitly set changed to false
            echo "changed_addons=[]" | tee -a "$GITHUB_OUTPUT"; # Output empty array for changed_addons if none
          fi
  debug:
    name: Debug the selected addon job values
    runs-on: ubuntu-latest
    needs:
      - init
    steps:
      - name: Dump init context
        run: |
          echo "Input addon: ${{ inputs.addon }}"
          echo "All Addons: ${{ needs.init.outputs.addons }}"
          echo "Changed Addons: ${{ needs.init.outputs.changed_addons }}"
          echo "Changed: ${{ needs.init.outputs.changed }}"
          echo "Tasked Addons ${{ inputs.addon && format('["{0}"]', inputs.addon) || (needs.init.outputs.changed == 'true' && needs.init.outputs.changed_addons) || (needs.init.outputs.addons && needs.init.outputs.addons) || '[]' }}"

  information:
    name: Gather add-on information for selected add-ons
    runs-on: ubuntu-latest
    needs:
      - init
    strategy:
      matrix:
        addon: ${{ inputs.addon && fromJson(format('["{0}"]', inputs.addon)) || (needs.init.outputs.changed == 'true' && fromJson(needs.init.outputs.changed_addons)) || (needs.init.outputs.addons && fromJson(needs.init.outputs.addons)) || fromJson('[]') }}
    outputs:
      architectures: ${{ steps.information.outputs.architectures }}
      base_image_signer: ${{ steps.information.outputs.codenotary_base_image }}
      build: ${{ steps.information.outputs.build }}
      description: ${{ steps.information.outputs.description }}
      name: ${{ steps.information.outputs.name }}
      slug: ${{ steps.override.outputs.slug }}
      target: ${{ steps.information.outputs.target }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run add-on information action
        id: information
        uses: frenck/action-addon-information@v1.4.2
        with:
          path: "./${{matrix.addon}}"
      - name: 🚀 Process possible slug override
        id: override
        run: |
          slug="${{ steps.information.outputs.slug }}"
          if [[ ! -z "${{ inputs.slug }}" ]]; then
            slug="${{ inputs.slug }}"
          fi
          echo "slug=$slug" >> "$GITHUB_OUTPUT"

  lint-addon:
    name: Lint Add-on
    needs:
      - information
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run Add-on Lint
        uses: frenck/action-addon-linter@v2.18.0
        with:
          community: true
          path: "./${{ needs.information.outputs.target }}"

  lint-hadolint:
    name: Hadolint
    needs:
      - information
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run Hadolint
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: "./${{ needs.information.outputs.target }}/Dockerfile"

  lint-json:
    name: JSON Lint
    runs-on: ubuntu-latest
    needs:
      - information
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run JQ
        run: |
          shopt -s globstar
          cat "${{ needs.information.outputs.target }}/**/*.json" | jq '.'

  lint-shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    needs:
      - information
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -s bash
        with:
          scandir: ${{ needs.information.outputs.target }}

  lint-yamllint:
    name: YAMLLint
    runs-on: ubuntu-latest
    needs:
      - information
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run YAMLLint
        uses: frenck/action-yamllint@v1.5
        with:
          path: ${{ needs.information.outputs.target }}

  lint-prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs:
      - information
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run Prettier
        uses: creyD/prettier_action@v4.5
        with:
          prettier_options: --write ${{ needs.information.outputs.target }}/**/*.{json,js,md,yaml}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_matrix:
    name: Generate Build Matrix
    runs-on: "ubuntu-latest"
    needs: information
    outputs:
      build_matrix: ${{ steps.generate.outputs.matrix_json }}
    steps:
      - name: Generate matrix
        id: generate
        env:
          SLUGS_JSON: ${{ toJson(needs.information.outputs.slug) }}
          TARGETS_JSON: ${{ toJson(needs.information.outputs.target) }}
          ARCHITECTURES_ARRAY_JSON: ${{ needs.information.outputs.architectures }}
          NAMES_JSON: ${{ toJson(needs.information.outputs.name) }}
          DESCRIPTIONS_JSON: ${{ toJson(needs.information.outputs.description) }}
          BUILD_CONFIGS_JSON: ${{ toJson(needs.information.outputs.build) }}
        run: |
          matrix_array="[]"

          mapfile -t slug_arr < <(echo "$SLUGS_JSON" | jq -r '.')
          mapfile -t target_arr < <(echo "$TARGETS_JSON" | jq -r '.')
          mapfile -t name_arr < <(echo "$NAMES_JSON" | jq -r '.')
          mapfile -t desc_arr < <(echo "$DESCRIPTIONS_JSON" | jq -r '.')
          mapfile -t build_arr < <(echo "$BUILD_CONFIGS_JSON" | jq -r '.')
          mapfile -t arch_json_str_arr < <(echo "$ARCHITECTURES_JSON_ARRAY_JSON" | jq -r '.')

          for i in "${!slug_arr[@]}"; do
            current_slug="${slug_arr[$i]}"
            current_target="${target_arr[$i]}"
            current_arch_json_str="${arch_json_str_arr[$i]}"
            current_name="${name_arr[$i]}"
            current_desc="${desc_arr[$i]}"
            current_build_json_str="${build_arr[$i]}"

            current_architectures=$(echo "$current_arch_json_str" | jq -r '.[]')
            for arch in $current_architectures; do
              matrix_entry=$(jq -n \
                --arg slug "$current_slug" \
                --arg target "$current_target" \
                --arg name "$current_name" \
                --arg description "$current_desc" \
                --arg architecture "$arch" \
                --arg build_config_str "$current_build_json_str" \
                '{
                  "addon_info": {
                    "slug": $slug,
                    "target": $target,
                    "name": $name,
                    "description": $description,
                    "build": $build_config_str
                  },
                  "architecture": $architecture
                }')
              matrix_array=$(echo "$matrix_array" | jq --argjson entry "$matrix_entry" '. + [$entry]')
            done
          done
          echo "matrix=$matrix_array" >> $GITHUB_OUTPUT
          echo "Generated matrix: $matrix_array"
  build:
    name: Build ${{ matrix.addon_info.name }} (${{ matrix.architecture }})
    needs:
      - build_matrix
      - lint-addon
      - lint-hadolint
      - lint-json
      - lint-prettier
      - lint-shellcheck
      - lint-yamllint
    runs-on: ${{ contains(fromJson('["armhf", "armv7", "aarch64"]'), matrix.architecture) && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.build_matrix.outputs.build_matrix) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🏗 Set up build cache
        id: cache
        uses: actions/cache@v4.2.3
        with:
          path: /tmp/.docker-cache # Cache path
          key: docker-${{ matrix.addon_info.slug }}-${{ matrix.architecture }}-${{ github.sha }}
          restore-keys: |
            docker-${{ matrix.addon_info.slug }}-${{ matrix.architecture }}
      - name: 🏗 Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: 🏗 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: ℹ️ Compose build flags
        id: flags
        run: |
          echo "date=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_OUTPUT"
          from=$(yq --no-colors eval ".build_from.${{ matrix.architecture }}" "${{ matrix.addon_info.build }}")
          echo "from=${from}" >> "$GITHUB_OUTPUT"

          if [[ "${{ matrix.architecture}}" = "amd64" ]]; then
            echo "platform=linux/amd64" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "i386" ]]; then
            echo "platform=linux/386" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "armhf" ]]; then
            echo "platform=linux/arm/v6" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "armv7" ]]; then
            echo "platform=linux/arm/v7" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.architecture }}" = "aarch64" ]]; then
            echo "platform=linux/arm64/v8" >> "$GITHUB_OUTPUT"
          else
            echo "::error ::Could not determine platform for architecture ${{ matrix.architecture }}"
            exit 1
          fi
      - name: Compose build args
        id: buildargs
        run: |
          set -eo pipefail

          COMBINED_ARGS_TEMP_FILE=$(mktemp)
          # Ensure cleanup on exit, even if script fails
          trap 'rm -f "$COMBINED_ARGS_TEMP_FILE"' EXIT

          {
            # Part 1: Args from build config (matrix.addon_info.build)
            # yq extracts the .args map from the JSON string, formats as 'key: value' lines, then sed converts to 'key=value'.
            echo "${{ matrix.addon_info.build }}" | yq --no-colors '.args | to_entries | .[] | .key + ": " + .value' | sed -r 's#: #=#' > "$COMBINED_ARGS_TEMP_FILE"

            # Part 2: Static args
            echo "BUILD_ARCH=${{ matrix.architecture }}" >> "$COMBINED_ARGS_TEMP_FILE"
            echo "BUILD_DATE=${{ steps.flags.outputs.date }}" >> "$COMBINED_ARGS_TEMP_FILE"
            echo "BUILD_DESCRIPTION=${{ matrix.addon_info.description }}" >> "$COMBINED_ARGS_TEMP_FILE"
            echo "BUILD_FROM=${{ steps.flags.outputs.from }}" >> "$COMBINED_ARGS_TEMP_FILE"
            echo "BUILD_NAME=${{ matrix.addon_info.name }}" >> "$COMBINED_ARGS_TEMP_FILE"
            echo "BUILD_REF=${{ github.sha }}" >> "$COMBINED_ARGS_TEMP_FILE"
            echo "BUILD_REPOSITORY=${{ github.repository }}" >> "$COMBINED_ARGS_TEMP_FILE"
            echo "BUILD_VERSION=edge" >> "$COMBINED_ARGS_TEMP_FILE"

          } > "$COMBINED_ARGS_TEMP_FILE"

          echo -n "args=" >> "$GITHUB_OUTPUT"
          # Filter out any blank lines from the final list of arguments
          awk 'NF' "$COMBINED_ARGS_TEMP_FILE" >> "$GITHUB_OUTPUT"
      - name: ⤵️ Download base image
        if: steps.flags.outputs.from != 'null'
        run: docker pull "${{ steps.flags.outputs.from }}"
      - name: 🚀 Build
        uses: docker/build-push-action@v6.18.0
        with:
          push: false
          context: ${{ matrix.addon_info.target }}
          file: ${{ matrix.addon_info.target }}/Dockerfile
          cache-from: |
            type=local,src=/tmp/.docker-cache
            ghcr.io/${{ github.repository_owner }}/${{ matrix.addon_info.slug }}/${{ matrix.architecture }}:edge
          cache-to: type=local,mode=max,dest=/tmp/.docker-cache-new
          platforms: ${{ steps.flags.outputs.platform }}
          build-args: ${{ steps.buildargs.outputs.args }}

      # This ugly bit is necessary, or our cache will grow forever...
      # Well until we hit GitHub's limit of 5GB :)
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: 🚚 Swap build cache
        run: |
          rm -rf /tmp/.docker-cache
          mv /tmp/.docker-cache-new /tmp/.docker-cache
