---
name: Traefik CI
# yamllint disable-line rule:truthy
on:
  push:
    # temporary
    # paths:
    #   - "traefik/**"
    branches:
      - master
  pull_request:
    paths:
      - "traefik/**"
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: dcode/home-assistant-addons/.github/workflows/build-common.yaml@master
    with:
      addon_directory: "traefik"
