---
name: Traefik CI

on:
  push:
    paths:
      - 'traefik/**'
    branches:
      - master
  pull_request:
    paths:
      - 'traefik/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  ADD_ON_DIRECTORY: traefik

jobs:
  workflows:
    uses: dcode/home-assistant-addons/.github/workflows/ci-common.yaml@master
